[workspace]
members = ["core"]
resolver = "2"

[workspace.package]
name = "civita"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
civita-core = { path = "./core" }
