[package]
name = "civita"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.55", features = [
  "identify",
  "macros",
  "kad",
  "tcp",
  "tokio",
  "noise",
  "yamux",
  "request-response",
  "gossipsub",
  "serde",
] }
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
rand = "0.9"
sha2 = "0.10"
crossbeam-channel = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"

[dev-dependencies]
tempfile = "3.17"
