[workspace]
members = ["core", "cli"]
resolver = "2"

[workspace.package]
name = "civita"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
civita-core = { path = "./core" }
civita-cli = { path = "./cli" }
