[package]
name = "civita-cli"
version.workspace = true
edition.workspace = true

[dependencies]
civita-core = { path = "../core" }
clap = { version = "4.5" }
base64 = "0.22"
tokio = { version = "1", features = ["full"] }
