name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
      if: runner.os == 'Linux'

    - name: Cache Rust dependencies
      id: cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Rust
      uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
      with:
        toolchain: nightly

    - name: Install tarpaulin
      run: |
        if ! command -v cargo-tarpaulin >/dev/null 2>&1; then
          cargo install cargo-tarpaulin
        fi

    - name: Run tests and generate coverage
      run: cargo tarpaulin --out Lcov --output-dir ./coverage

    - name: Upload coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./coverage/lcov.info
